Fix divide by zero in Task_Align::match_contrast() (#7)
This caused the error message:
Task Align frame-0027.jpg to frame-0026.jpg on thread 3 failed with
exception:OpenCV(4.2.0) ../modules/video/src/ecc.cpp:557: error:
(-7:Iterations do not converge) NaN encountered. in function
'findTransformECC'